services:
  db:
    image: postgres:17
    container_name: postgres_container
    environment:
      - POSTGRES_USER=luciano
      - POSTGRES_PASSWORD=introcamejo
      - POSTGRES_DB=foro
    ports:
      - 5432:5432
    volumes:
      - ./psql_data:/var/lib/postgresql/data
